language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
script: bundle exec rspec
branches:
  only:
    - master
notifications:
  mails:
    - i2bskn@gmail.com
  on_sucess: always
  on_failure: always